apiVersion: v1
kind: Namespace
metadata:
  name: fe-team
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fe-team
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sulemahnh/frontend-pg:v5
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fe-team
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: ClusterIP
---

